
desc 'Get CUCUMBER-9 dataset(binary for python)'
task :cucumber do
  puts `git clone https://github.com/workpiles/CUCUMBER-9.git`
  puts "Extract.."
  cd "CUCUMBER-9/prototype_1"
  puts `tar xzf cucumber-9-python.tar.gz`
  rm "cucumber-9-python.tar.gz"
  cd "../prototype_2"
  puts `tar xzf cucumber-9-p2-python.tar.gz`
  rm "cucumber-9-p2-python.tar.gz"
end

desc 'Get coffee beans image set(jpeg)'
task :coffee do
  puts "Extract.."
  cd "coffees"
  puts `tar xzf images.tgz`
  rm "images.tgz"
end

# http://yann.lecun.com/exdb/mnist/
desc 'Get mnist handwritten digits'
task :mnist do
  `curl -O http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz`
end

# https://www.cs.toronto.edu/~kriz/cifar.html
desc 'Get cifar-10 image dataset'
task :mnist do
  `curl -O https://www.cs.toronto.edu/~kriz/cifar-10-binary.tar.gz`
end
