

desc 'Sync files to ubuntu server.'
task :ubuntu do
  cmd = "rsync -avz --exclude='histories/' --exclude='models/' webapp/ ubuntu@133.242.22.108:/var/www/html/tensorflow/"
  puts `#{cmd}`
end

task :default => [:ubuntu]
