TWILIO_SID = ENV['TWILIO_SID']
TWILIO_TOKEN = ENV['TWILIO_TOKEN']
TWILIO_NUMBER = ENV['TWILIO_NUMBER']

LINE_CHANNEL_SECRET = ENV['LINE_CHANNEL_SECRET']
LINE_CHANNEL_TOKEN = ENV['LINE_CHANNEL_TOKEN']
