# ubuntu18-rails5-mysql57 rev:20.12.26
version: '3.8'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./tmp/mysql:/var/lib/mysql
  web:
    image: lm-ubuntu18:latest
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/home
      - bundle:/var/lib/gems/2.5.0
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle:
